# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: cd $GITHUB_WORKSPACE/angular/node_modules
        key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: v1-npm-deps-
    - run: cd $GITHUB_WORKSPACE/angular && npm install
    - run: cd $GITHUB_WORKSPACE/angular && npm run build-github-page --if-present
    - run: cd $GITHUB_WORKSPACE/angular && ls
    - run: cd $GITHUB_WORKSPACE/angular/dist && ls
    - run: cd $GITHUB_WORKSPACE/angular/dist/angular && ls
    #- run: cd $GITHUB_WORKSPACE/angular && npm test # commented: get stuck
    - run : cp -r $GITHUB_WORKSPACE/angular/dist/angular $GITHUB_WORKSPACE/docs 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.name }}-dist
        #path: ${{ github.workspace }}/angular/dist/angular/**/*
        path: ${{ github.workspace }}/docs/**/*
